import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/context/theme-provider";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
     <html lang="en" suppressHydrationWarning>
       <body className={jakarta.className}>
        <ThemeProvider attribute="class" defaultTheme="light" disableTransitionOnChange>
          <Toaster/>
          {children}
        </ThemeProvider>
       </body>
     </html>
    </ClerkProvider>
  );
}
